package authorizer

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestValidateToken(t *testing.T) {

	auth, err := NewAuthorizerWithAudience("https://login.dcode.tech", "terraform-registry-automation")
	assert.Nil(t, err)
	assert.NotNil(t, auth)

	claims, err := auth.ParseAndVerifyToken("eyJhbGciOiJSUzI1NiIsImtpZCI6ImEzZDdjY2ZmYWY2NjcxZDY1MTNjNWI2NGU4MjZlNTViNGNmMmE4ZTYifQ.eyJpc3MiOiJodHRwczovL2xvZ2luLmRjb2RlLnRlY2giLCJzdWIiOiJDaFV4TURrMU9UY3hOemMwTlRjMk1EZzFNakV6TVRNU0JtZHZiMmRzWlEiLCJhdWQiOiJ0ZXJyYWZvcm0tcmVnaXN0cnktYXV0b21hdGlvbiIsImV4cCI6MTczMzc1NTE4MiwiaWF0IjoxNzMzNjY4NzgyLCJub25jZSI6IlhaTmlvdXN1QVR1MmlpNHlQYXdZTTMiLCJhdF9oYXNoIjoiU3FCb3oxV0xkZXRvTzJLM0lKUmFWdyIsImVtYWlsIjoibWFvckBkY29kZS50ZWNoIiwiZW1haWxfdmVyaWZpZWQiOnRydWV9.F0VSAt8i1u0pqpN00VgElZ4U8nSsfIjZK050XLmF9uk8N5-YUpH-tq8AK53fdHMuHWCzR42CAZ-4KHjPUP0mavktoYaV-Xqh-Tv2yZotPLPastGcRoq48rAmcRdwZGzqtturNA_Pccs_n45BGsz8w9ObpJdDy76OKktPLJVMti4Kmo8kmdAfnpyh7minya96dF_phhNrgI0i_DoymNC-ByH4Vn6Ja_Jz-ONerw4-H31EYBiXp9U7nx4mDV1FszJKSUXiOqjBXwIWbHR7IbLW49vJrp4NBgpxtY_AxozI7j6-h1MreyWWZAQ6cldHp9bbB5GfKNqUoB-s35Y3VbwSgw")
	assert.Nil(t, err)
	assert.NotNil(t, claims)
}
